name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: CompeyDev/setup-rokit@v0.1.2
      - run: selene .
      - run: stylua --check .
      - run: pesde install
      - run: rojo build --output build.rbxm release.project.json
      - run: echo "VERSION=v$(cat pesde.toml | grep -Po 'version = \"\K([0-9.]+)')" >> "$GITHUB_ENV"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.rbxm"
          tag: ${{ env.VERSION }}
